## import relevant libaries

In [3]:
import numpy as np

### creating a tensor

In [4]:
m1=np.array([[5,7,9],[8,6,5]])

In [5]:
m1

array([[5, 7, 9],
       [8, 6, 5]])

In [6]:
m2=np.array([[9,3,1],[6,4,0]])
m2

array([[9, 3, 1],
       [6, 4, 0]])

In [7]:
t=np.array([m1,m2])

In [8]:
t

array([[[5, 7, 9],
        [8, 6, 5]],

       [[9, 3, 1],
        [6, 4, 0]]])

### checking its shape

In [9]:
t.shape

(2, 2, 3)

### manually creating a tensor

In [10]:
t_manual=np.array([[[9,0,6],[8,9,5]],[[76,5,4],[3,45,7]],[[45,56,90],[98,6,7]]])

In [11]:
t_manual

array([[[ 9,  0,  6],
        [ 8,  9,  5]],

       [[76,  5,  4],
        [ 3, 45,  7]],

       [[45, 56, 90],
        [98,  6,  7]]])

### adding and subtracting

In [12]:
m3=m1-m2

In [13]:
m3

array([[-4,  4,  8],
       [ 2,  2,  5]])

## transposing matrices

In [14]:
mk=m1.T

In [16]:
m1

array([[5, 7, 9],
       [8, 6, 5]])

In [15]:
mk

array([[5, 8],
       [7, 6],
       [9, 5]])

In [17]:
m2

array([[9, 3, 1],
       [6, 4, 0]])

In [18]:
m2.T

array([[9, 6],
       [3, 4],
       [1, 0]])

### transposing scalars

In [20]:
s=np.array([9])

In [21]:
s.T

array([9])

#### transposing vectors

In [22]:
x=np.array([7,4,6])
x

array([7, 4, 6])

In [23]:
x.T

array([7, 4, 6])

In [24]:
x.shape

(3,)

In [25]:
x_reshaped=x.reshape(1,3)

In [26]:
x_reshaped

array([[7, 4, 6]])

In [27]:
x_reshaped.T

array([[7],
       [4],
       [6]])

## multiplication

### dot product

In [29]:
x=np.array([4,5,8])
y=np.array([3,2,6])

In [30]:
np.dot(x,y)

70

In [31]:
l=np.array([76,89,4])
p=np.array([34,52,0])

In [32]:
np.dot(l,p)

7212

### scalar*scalar

In [33]:
np.dot(5,7)

35

In [35]:
np.dot(9,2)

18

### scalar and vector

In [36]:
x

array([4, 5, 8])

In [37]:
7*x

array([28, 35, 56])

#### scalar*matrix

In [38]:
b=np.array([[4,-5,-0],[3,-8,9]])
b

array([[ 4, -5,  0],
       [ 3, -8,  9]])

In [39]:
3*b

array([[ 12, -15,   0],
       [  9, -24,  27]])

### matrix*matrix

In [43]:
a=np.array([[9,6,0],[-8,5,4]])
A=a.T

In [44]:
A

array([[ 9, -8],
       [ 6,  5],
       [ 0,  4]])

In [45]:
np.dot(A,b)

array([[ 12,  19, -72],
       [ 39, -70,  45],
       [ 12, -32,  36]])

In [46]:
z=np.array([[1,-4],[-2,1]])
y=np.array([[0,3],[5,8]])

In [47]:
z

array([[ 1, -4],
       [-2,  1]])

In [48]:
y

array([[0, 3],
       [5, 8]])

In [50]:
z-y

array([[ 1, -7],
       [-7, -7]])

In [51]:
z+y

array([[ 1, -1],
       [ 3,  9]])