## import relevant libaries

In [1]:
import numpy as np

### creating a tensor

In [2]:
m1=np.array([[5,7,9],[8,6,5]])

In [3]:
m1

array([[5, 7, 9],
       [8, 6, 5]])

In [4]:
m2=np.array([[9,3,1],[6,4,0]])
m2

array([[9, 3, 1],
       [6, 4, 0]])

In [5]:
t=np.array([m1,m2])

In [6]:
t

array([[[5, 7, 9],
        [8, 6, 5]],

       [[9, 3, 1],
        [6, 4, 0]]])

### checking its shape

In [8]:
t.shape

(2, 2, 3)

### manually creating a tensor

In [10]:
t_manual=np.array([[[9,0,6],[8,9,5]],[[76,5,4],[3,45,7]],[[45,56,90],[98,6,7]]])

In [11]:
t_manual

array([[[ 9,  0,  6],
        [ 8,  9,  5]],

       [[76,  5,  4],
        [ 3, 45,  7]],

       [[45, 56, 90],
        [98,  6,  7]]])