In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow import keras
sns.set()

### data generation

In [3]:
observations=1000
xs=np.random.uniform(low=-10,high=10,size=(observations,1))
zs=np.random.uniform(-10,10,(observations,1))
g_inputs=np.column_stack((xs,zs))
noise=np.random.uniform(-1,1,(observations,1))
g_targets= 2*xs - 3*zs + 5 + noise
np.savez('TF_intro', inputs=g_inputs,targets=g_targets)

### solving with tensorflow

In [4]:
training_data=np.load('TF_intro.npz')

In [7]:
input_size=2
output_size=1

model=tf.keras.Sequential([
                           tf.keras.layers.Dense(output_size,
                                                 kernel_initializer=tf.random_uniform_initializer(minval=-0.1,maxval=0.1),
                                                 bias_initializer=tf.random_uniform_initializer(minval=-0.1,maxval=0.1))
                          ])
custom_optimizer=tf.keras.optimizers.SGD(learning_rate=0.02)
model.compile(optimizer=custom_optimizer,loss='mean_squared_error')
model.fit(training_data['inputs'],training_data['targets'],epochs=100,verbose=2)

Epoch 1/100
32/32 - 1s - loss: 25.4214 - 1s/epoch - 37ms/step
Epoch 2/100
32/32 - 0s - loss: 1.2547 - 94ms/epoch - 3ms/step
Epoch 3/100
32/32 - 0s - loss: 0.4821 - 95ms/epoch - 3ms/step
Epoch 4/100
32/32 - 0s - loss: 0.3879 - 99ms/epoch - 3ms/step
Epoch 5/100
32/32 - 0s - loss: 0.3909 - 93ms/epoch - 3ms/step
Epoch 6/100
32/32 - 0s - loss: 0.3826 - 79ms/epoch - 2ms/step
Epoch 7/100
32/32 - 0s - loss: 0.4325 - 91ms/epoch - 3ms/step
Epoch 8/100
32/32 - 0s - loss: 0.3731 - 70ms/epoch - 2ms/step
Epoch 9/100
32/32 - 0s - loss: 0.3999 - 100ms/epoch - 3ms/step
Epoch 10/100
32/32 - 0s - loss: 0.3708 - 79ms/epoch - 2ms/step
Epoch 11/100
32/32 - 0s - loss: 0.3843 - 76ms/epoch - 2ms/step
Epoch 12/100
32/32 - 0s - loss: 0.3775 - 90ms/epoch - 3ms/step
Epoch 13/100
32/32 - 0s - loss: 0.3750 - 81ms/epoch - 3ms/step
Epoch 14/100
32/32 - 0s - loss: 0.3697 - 77ms/epoch - 2ms/step
Epoch 15/100
32/32 - 0s - loss: 0.4112 - 65ms/epoch - 2ms/step
Epoch 16/100
32/32 - 0s - loss: 0.3926 - 69ms/epoch - 2ms/step


### extract the weights and bias

In [9]:
model.layers[0].get_weights()

[array([[ 2.050263 ],
        [-2.9629538]], dtype=float32),
 array([5.0280776], dtype=float32)]

In [10]:
weights=model.layers[0].get_weights()[0]
weights

array([[ 2.050263 ],
       [-2.9629538]], dtype=float32)

In [11]:
bias=model.layers[0].get_weights()[1]
bias

array([5.0280776], dtype=float32)

In [12]:
model.predict_on_batch(training_data['inputs']).round(1)

array([[ 20.6],
       [-22.2],
       [ -3.4],
       [ 11.8],
       [-10.4],
       [ 22.2],
       [ 13.4],
       [ 31.8],
       [-21.5],
       [  2.5],
       [ 24. ],
       [-10.3],
       [-25.9],
       [-20.4],
       [ 20.8],
       [ 35. ],
       [ 48.2],
       [ 30.4],
       [  7.5],
       [-10.5],
       [-26.9],
       [ 33.5],
       [ 22.9],
       [ 17.7],
       [  8.8],
       [ -8.2],
       [ 53.2],
       [-16.5],
       [  3.2],
       [ 40.4],
       [-15.2],
       [ 47.8],
       [ 31.7],
       [-10.7],
       [-18.7],
       [  1.5],
       [ 26.7],
       [ -2.7],
       [-37.4],
       [ -2. ],
       [  5.1],
       [ 23.7],
       [ 22.8],
       [ -0.9],
       [ 17.1],
       [-35.6],
       [ 29.4],
       [ 11. ],
       [ -8.8],
       [ -4.9],
       [-21.8],
       [-10.6],
       [ 25.3],
       [ -4. ],
       [ 30.1],
       [  8.4],
       [ -6.7],
       [ 17.7],
       [  6.1],
       [ -1.9],
       [ 42.4],
       [ -1.7],
       [

#### extract the outputs

In [ ]:
#plt.plot(np.squeeze(model.predict_on_batch(training_data['inputs'])),np.squeeze(training_data['targets']))
#plt.xlabel('outputs')
#plt.ylabel('targets')
#plt.show()